name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-page
          git merge main --no-ff

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build Project
        run: yarn && yarn build

      - name: Rename
        run: |
          rm -rf docs
          mv out docs

      - name: Push
        run: |
          git add .
          git commit -m "Update Docs"
          git push origin gh-page
